### ISSUE TITLE
Can you update?

### ISSUE THREAD

**Issue by Mioni** [ZEBAS204/twitch-miner-compiled#1]
It is no longer collecting points, I think it is outdated.

**Comment by ZEBAS204** [comment]
The script is still working as expected, but PyInstaller, which I use to create the executables, is failing for some reason.

You will need to wait until I can figure out what is the problem.
In the meantime, I'll leave this issue open

**Comment by ZEBAS204** [comment]
Temp fix for windows

https://files.catbox.moe/7wt7kg.zip

**Comment by ZEBAS204** [comment]
Released

https://github.com/ZEBAS204/twitch-miner-compiled/releases/tag/v1.9.9
